---
name: ChatThin
main: blugin\chatthin\ChatThin
version: 1.3.0
api: [4.0.0]
authors: ['Blugin-team', 'PresentKim']
description: Make all messages have the same font
mcpe-protocol: [407, 408, 419, 422, 448]
...